[project]
name = "yafipadump"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "capstone>=5.0.9",
    "frida>=17.22.2",
    "lief>=1.0.0",
    "pwn>=1.0",
    "rich>=15.0.0",
]

[project.scripts]
yafipadump = "yafipadump.__main__:main"

[tool.setuptools.packages.find]
include = ["yafipadump*"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
